"""
Inflect Phase 1C — Kokoro Alignment Fine-Tune

Fine-tunes encoder + adapter jointly on perfectly-labelled
(mel, voice_pack) pairs generated by generate_kokoro_pairs.py.

The encoder learns "what each Kokoro voice sounds like."
The adapter learns to map those embeddings to the correct pack.

Losses:
  1. MSE:       adapter output vs full voice pack [511,256]
  2. Cosine:    push embedding toward true voice centroid
  3. Contrastive: push away from wrong voices (InfoNCE-style)
  4. Diversity: prevent batch collapse

LR strategy:
  Encoder: 5e-5  (low — preserve GE2E speaker features)
  Adapter: 2e-4  (higher — needs more re-shaping)

Runtime: ~30-45 min on RTX 3060.
Usage:
    python train_1c_alignment.py
"""

import random
import sys
from pathlib import Path

import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parent))

BASE      = Path(r"C:\Users\Owen\Inflect-New\voice-encoder")
CKPT_DIR  = BASE / "checkpoints"
VOICE_DIR = BASE / "data" / "kokoro_voices"
MANIFEST  = BASE / "data" / "1c_manifest.csv"

ENCODER_CKPT = CKPT_DIR / "ve_latest.pt"
ADAPTER_CKPT = CKPT_DIR / "adapter_v2_best.pt"

EMBED_DIM  = 256
LR_ENCODER = 5e-5
LR_ADAPTER = 2e-4
EPOCHS     = 300
BATCH_SIZE = 32
SAVE_EVERY = 50
TEMP       = 0.07   # InfoNCE temperature
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"Device: {DEVICE}")


# ── Dataset ───────────────────────────────────────────────────────────────────

class AlignmentDataset(Dataset):
    def __init__(self, records, pack_map):
        self.records  = records
        self.pack_map = pack_map   # voice_name -> [511,256]

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        row  = self.records[idx]
        mel  = torch.load(row["mel_path"], weights_only=True)  # [80,160]
        pack = self.pack_map[row["voice_name"]]                # [511,256]
        return mel, pack


def collate_fn(batch):
    mels  = torch.stack([b[0] for b in batch])  # [B,80,160]
    packs = torch.stack([b[1] for b in batch])  # [B,511,256]
    return mels, packs


# ── Load voice packs ──────────────────────────────────────────────────────────

def load_voice_packs():
    pack_map     = {}
    centroid_map = {}
    for vf in sorted(VOICE_DIR.glob("**/*.pt")):
        pack    = torch.load(vf, map_location="cpu", weights_only=True)  # [511,1,256]
        pack_2d = pack[:, 0, :]                                           # [511,256]
        centroid = F.normalize(pack_2d.mean(dim=0), dim=0)               # [256]
        pack_map[vf.stem]     = pack_2d
        centroid_map[vf.stem] = centroid
    return pack_map, centroid_map


# ── InfoNCE contrastive loss ──────────────────────────────────────────────────

def infonce_loss(embeddings, centroids, temperature=TEMP):
    """
    embeddings: [B,256] L2-normalized adapter outputs
    centroids:  [B,256] L2-normalized true voice centroids
    Each item in the batch is a positive pair; all others are negatives.
    """
    logits = torch.mm(embeddings, centroids.T) / temperature  # [B,B]
    labels = torch.arange(len(embeddings), device=embeddings.device)
    return F.cross_entropy(logits, labels)


# ── Training ──────────────────────────────────────────────────────────────────

def train():
    df = pd.read_csv(MANIFEST)
    print(f"Manifest: {len(df)} clips, {df['voice_name'].nunique()} voices")

    pack_map, centroid_map = load_voice_packs()
    print(f"Loaded {len(pack_map)} voice packs")

    # Dataset split
    records = df.to_dict("records")
    random.shuffle(records)
    split    = int(0.9 * len(records))
    train_ds = AlignmentDataset(records[:split], pack_map)
    val_ds   = AlignmentDataset(records[split:], pack_map)

    train_loader = DataLoader(
        train_ds, batch_size=BATCH_SIZE, shuffle=True,
        num_workers=0, collate_fn=collate_fn, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=BATCH_SIZE, shuffle=False,
        num_workers=0, collate_fn=collate_fn,
    )

    # Load encoder
    from train_ve import VoiceEncoder
    encoder = VoiceEncoder().to(DEVICE)
    enc_ckpt = torch.load(ENCODER_CKPT, map_location=DEVICE, weights_only=False)
    encoder.load_state_dict(enc_ckpt["model"])
    print(f"Encoder loaded (epoch {enc_ckpt.get('epoch','?')})")

    # Load adapter
    from train_1b_adapter_v2 import StyleAdapterV2
    adapter = StyleAdapterV2().to(DEVICE)
    adp_ckpt = torch.load(ADAPTER_CKPT, map_location=DEVICE, weights_only=False)
    adapter.load_state_dict(adp_ckpt["adapter"])
    print(f"Adapter v2 loaded (epoch {adp_ckpt.get('epoch','?')}, loss={adp_ckpt.get('loss',0):.4f})")

    # Separate LRs: encoder gets 4× smaller LR to preserve GE2E features
    optimizer = torch.optim.AdamW([
        {"params": encoder.parameters(), "lr": LR_ENCODER},
        {"params": adapter.parameters(), "lr": LR_ADAPTER},
    ], weight_decay=1e-5)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=EPOCHS, eta_min=1e-6
    )

    n_enc = sum(p.numel() for p in encoder.parameters()) / 1e6
    n_adp = sum(p.numel() for p in adapter.parameters()) / 1e3
    print(f"Encoder: {n_enc:.1f}M params  Adapter: {n_adp:.1f}K params")
    print(f"Training {EPOCHS} epochs | batch={BATCH_SIZE} | "
          f"train={len(train_ds)} val={len(val_ds)}\n")

    best_val_sim = 0.0

    for epoch in range(EPOCHS):
        # ── Train ──────────────────────────────────────────────────────────────
        encoder.train()
        adapter.train()

        t_loss = t_sim = 0.0
        n_batches = 0

        for mels, target_packs in train_loader:
            mels         = mels.to(DEVICE)          # [B,80,160]
            target_packs = target_packs.to(DEVICE)  # [B,511,256]

            enc_emb = encoder.embed(mels)             # [B,256]
            adapted = adapter.forward_embed(enc_emb)  # [B,256] L2-norm

            # True centroids for this batch (L2-normalized)
            tgt_cent = F.normalize(target_packs.mean(dim=1), dim=-1)  # [B,256]

            # Loss 1: MSE against full voice pack
            T_steps    = target_packs.shape[1]
            pred_packs = adapted.unsqueeze(1).expand(-1, T_steps, -1)
            mse_loss   = F.mse_loss(pred_packs, target_packs)

            # Loss 2: Cosine alignment to true centroid
            cos_loss = (1.0 - (adapted * tgt_cent).sum(dim=-1)).mean()

            # Loss 3: InfoNCE contrastive (batch positives vs negatives)
            nce_loss = infonce_loss(adapted, tgt_cent)

            # Loss 4: Diversity (prevent all outputs collapsing)
            gram     = torch.mm(adapted, adapted.T)
            eye      = torch.eye(BATCH_SIZE, device=DEVICE)
            div_loss = ((gram - eye) ** 2).mean()

            loss = mse_loss + 0.5 * cos_loss + 0.3 * nce_loss + 0.02 * div_loss

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(
                list(encoder.parameters()) + list(adapter.parameters()), 1.0
            )
            optimizer.step()

            with torch.no_grad():
                sim = (adapted * tgt_cent).sum(dim=-1).mean().item()
            t_loss    += loss.item()
            t_sim     += sim
            n_batches += 1

        scheduler.step()

        # ── Validate ───────────────────────────────────────────────────────────
        encoder.eval()
        adapter.eval()

        v_loss = v_sim = 0.0
        n_val  = 0

        with torch.no_grad():
            for mels, target_packs in val_loader:
                mels         = mels.to(DEVICE)
                target_packs = target_packs.to(DEVICE)

                enc_emb  = encoder.embed(mels)
                adapted  = adapter.forward_embed(enc_emb)
                tgt_cent = F.normalize(target_packs.mean(dim=1), dim=-1)

                T_steps    = target_packs.shape[1]
                pred_packs = adapted.unsqueeze(1).expand(-1, T_steps, -1)
                mse        = F.mse_loss(pred_packs, target_packs)
                cos        = (1.0 - (adapted * tgt_cent).sum(dim=-1)).mean()
                nce        = infonce_loss(adapted, tgt_cent)

                v_loss += (mse + 0.5 * cos + 0.3 * nce).item()
                v_sim  += (adapted * tgt_cent).sum(dim=-1).mean().item()
                n_val  += 1

        avg_t_loss = t_loss / max(n_batches, 1)
        avg_v_loss = v_loss / max(n_val, 1)
        avg_v_sim  = v_sim  / max(n_val, 1)

        if (epoch + 1) % 25 == 0 or epoch == 0:
            lr_enc = optimizer.param_groups[0]["lr"]
            lr_adp = optimizer.param_groups[1]["lr"]
            print(f"Epoch {epoch+1:03d} — "
                  f"train={avg_t_loss:.4f}  val={avg_v_loss:.4f}  "
                  f"val_sim={avg_v_sim:.4f}  "
                  f"lr_enc={lr_enc:.1e}  lr_adp={lr_adp:.1e}")

        # Save best by val_sim (higher = better alignment)
        if avg_v_sim > best_val_sim:
            best_val_sim = avg_v_sim
            torch.save({
                "epoch":    epoch + 1,
                "encoder":  encoder.state_dict(),
                "adapter":  adapter.state_dict(),
                "val_loss": avg_v_loss,
                "val_sim":  best_val_sim,
                "version":  "1c",
            }, CKPT_DIR / "1c_best.pt")

        if (epoch + 1) % SAVE_EVERY == 0:
            torch.save({
                "epoch":    epoch + 1,
                "encoder":  encoder.state_dict(),
                "adapter":  adapter.state_dict(),
                "val_loss": avg_v_loss,
                "val_sim":  avg_v_sim,
                "version":  "1c",
            }, CKPT_DIR / f"1c_epoch_{epoch+1:03d}.pt")

    torch.save({
        "epoch":    EPOCHS,
        "encoder":  encoder.state_dict(),
        "adapter":  adapter.state_dict(),
        "val_loss": avg_v_loss,
        "val_sim":  best_val_sim,
        "version":  "1c",
    }, CKPT_DIR / "1c_latest.pt")

    print(f"\nDone. Best val_sim: {best_val_sim:.4f}")
    print(f"  > 0.5 = decent  |  > 0.7 = good  |  > 0.85 = excellent")
    print(f"\nNext: python test_cloning.py --use-dataset")


if __name__ == "__main__":
    train()
